### ISSUE TITLE
Feature: Command-line option for invalid expressions fallback (replacing)

### ISSUE THREAD

**Issue by VelocityRa** [sizmailov/pybind11-stubgen#149]
I'm exporting a method with a default argument value of `std::this_thread::get_id()` via pybind11, and the type isn't recognized, it's printed as `def my_method(self, thread_id: ThreadId = ...) -> None` and the following error is printed:

`
pybind11_stubgen - [  ERROR] In [redacted] : Invalid expression '<[redacted].ThreadId object at 0x000002159D2BB430>'
`

It would be useful if I could pass something like `--replace-expressions std::this_thread::get_id() CurrentThread`.

**Comment by sizmailov** [comment]
I thought about such an option but decided not to implement it. The reason is that a simple replacement logic is not robust, and a complex logic can't fit into the CLI option. IMO, this is another "use `pybind11-stubgen` as a library" scenario.

In your particular case, the `<[redacted].ThreadId object at 0x000002159D2BB430>` comes from `my_method.__doc__`. You can avoid it from the beginning by using `pybind::arg_v("thread_id", std::this_thread::get_id(), "CurrentThread")` instead of `pybind11::arg("thread_id") = std::this_thread::get_id()`.

Note that `def my_method(self, thread_id: ThreadId = CurrentThread) -> None` would likely produce a static checker error, but this is out of the scope of the question.

**Comment by VelocityRa** [comment]
@sizmailov Using `arg_v` like that prevents the error being printed but doesn't seem to work though, I still get the `= ...`. Also tried using `--print-invalid-expressions-as-is`.

**Comment by sizmailov** [comment]
`pybind11-stubgen` treats default values reconstructed from docstring as "print-unsafe" to ensure syntactically (and, to some extent, semantically) valid stubs.

The exception is made for
 - strings that can be parsed via `ast.literal_eval`
 - enum-repr-like strings (e.g. `<MyEnum.Answer: 42>`)
 - strings matching user-provided REGEX via `--print-safe-value-reprs`

The `--print-invalid-expressions-as-is` name is a bit misleading because it only affects the expressions in annotations. I'll update the option description to reflect that.

@VelocityRa  Add `--print-safe-value-reprs="CurrentThread"` to your command line to override.

**Comment by VelocityRa** [comment]
Thank you. Not sure if it's because I invoke stubgen via `subprocess.run` or not, but I had to use `--print-safe-value-reprs` without the quotes after the `=`, otherwise they were getting used as part of the regex (I used an `r` string and single quotes to enclose the entire argument, no escaping.

Specifically I ended up using `--print-safe-value-reprs=ThreadId\.current\(\)` (instead of `--print-safe-value-reprs="ThreadId\.current\(\)"`)
