### ISSUE TITLE
Unused imports

### ISSUE THREAD

**Issue by ixje** [sizmailov/pybind11-stubgen#32]
I noticed the following is always included in the generated stubs. 

https://github.com/sizmailov/pybind11-stubgen/blob/65f01c7c34c436f85ac59e92136ce034d11a9145/pybind11_stubgen/__init__.py#L651-L654

For example in my case I don't use `numpy`, so this by default creates invalid stubs. The `_Shape` doesn't break any, but I also don't need it. Is this a left over or why does it exist? Thanks

**Comment by sizmailov** [comment]
Hi, thanks for report! 

This is an ad-hoc fix-up for pybind11-style numpy array annotations which are not supported by other tools due to [lack of convention](https://github.com/python/typing/issues/513). The line `from numpy import float64` is not needed if you using recent version of pybind (newer than https://github.com/pybind/pybind11/commit/22b2504080d37e035bbf3df88edb7abffb317ce5) or not binding functions that use numpy at all. 

I agree, those lines should be included only when needed. 
Also `from numpy import float64` imports most common type while strictly speaking it should be checked which types are really needed. I was lazy back then and included it unconditionally because it "anyway it wont hurt" and I needed it most of time.

Note that imports from `typing` falls into same "not always necessary" category.

I'll be happy to accept a PR.

**Comment by sizmailov** [comment]
Hi! I've updated generated stubs to avoid unnecessary imports. It's still imperfect but apparently more correct than it was before.
It's still unconditionally imports `typing`, probably that's fine. 

Feel free to reopen if you see any troubles with new release.

**Comment by ixje** [comment]
Sorry for not replying initially. I've been too bandwidth constrained to even start looking into it. Happy to see you made some improvements 👍
