### ISSUE TITLE
Suggestion: Support importing modules from the current directory

### ISSUE THREAD

**Issue by wallds** [sizmailov/pybind11-stubgen#77]
```
sys.path.append(os.path.abspath(os.curdir))
```

**Comment by sizmailov** [comment]
Hi!
I don't think it's a good idea.

Unconditionally adding current directory to `sys.path` is a no-go since it's likely not desired by most of users. 
If you suggest to add a command line option, I don't see how it's better than setting `PYTHONPATH` from shell or calling `sys.path.append` if used directly from python.

**Comment by wallds** [comment]
Thank you for your reply and solution.

> set PYTHONPATH=. 

Tested successfully in windows
